# fly.toml app configuration file generated for spotodo on 2023-08-30T00:15:58+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spotodo"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[processes]
  web = "bin/rails server"
  cron = "supercronic /rails/crontab"

[build]

[deploy]
  release_command = "./bin/rails db:migrate"

[http_service]
  processes = ["web"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
